version: '3.8'
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
  front-end:
    build: ./front-end
    ports:
      - "9000:9000"
